### ISSUE TITLE
Add split ABI so F-Droid can build arm64-v8a too

### ISSUE THREAD

**Issue by licaon-kter** [j05t/identify-dog-breeds-pro#8]

**Comment by j05t** [comment]
https://github.com/j05t/identify-dog-breeds-pro/releases/tag/v1.0.4

**Comment by licaon-kter** [comment]
A good start, now, setup versionCode to be different per arch, as F-Droid uses one build block per arch

eg. gradle: https://codeberg.org/iNPUTmice/Conversations/src/commit/5012c7d21d467ac437f9d46d0d82a5c3fdfb32ab/build.gradle#L254-L265

metadata: https://gitlab.com/fdroid/fdroiddata/-/blob/c291e7e8230baeae532819a561ce352294844795/metadata/eu.siacs.conversations.yml#L3250-L3296

**Comment by j05t** [comment]
I've updated the current release.

**Comment by licaon-kter** [comment]
thanks: https://gitlab.com/fdroid/fdroiddata/-/commit/49c553aab14aeabbd9ed88af63f71bd280f885dd
